variable "instance_type" {}
variable "tags" {}
variable "ami_image" {}
variable "vpc_security_group" {}
variable "global_name" {}
variable "private_key_name" {}
variable "disk_size" {}
variable "disk_type" {}
variable "k8s_type" {}
variable "k8s_full_ammount" {}