variable "instance_type" {}
variable "tags" {}
variable "ami_image" {}
variable "vpc_security_group" {}
variable "global_name" {}
variable "private_key_name" {}
variable "disk_size" {}
variable "disk_type" {}
variable "k8s_type" {}
variable "k8s_full_cluster_ammount" {}
variable "k8s_mini_cluster_ammount" {}
variable "k8s_minikube_nodes_ammount" {}
variable "iam_role_name" {}
variable "bucket_name" {}