variable "cidr_block" {}
variable "sg_port" {}
variable "propper_tags" {}
variable "global_name" {}
variable "vpc_id" {}
variable "tags" {}
variable "local_external_ip" {}
variable "default_subnets" {}
variable "k8s_full_external_ips" {}